# ci/Dockerfile-aws-cli
FROM docker:27-cli AS dockercli

FROM amazon/aws-cli:2.15.53
RUN (yum -y install jq || dnf -y install jq) && (yum clean all || true)

# docker CLI
COPY --from=dockercli /usr/local/bin/docker /usr/local/bin/docker

# docker buildx plugin (CLI plugin)
COPY --from=dockercli /usr/local/libexec/docker/cli-plugins/ /usr/local/libexec/docker/cli-plugins/